### PR TITLE
v3.22 Change SSL Certificate to OV TLS Certificate and EV SSL Certificate to EV TLS Certificate

### PR DESCRIPTION
**Pull request by vanbroup**
_(sync with Markdown version with Word version)_

This pull request includes several updates to the `entrust.md` file, primarily focusing on changing terminology from "SSL" to "TLS" for various certificate types. The updates also include version and date changes, as well as terminology adjustments throughout the document to reflect these changes.

Terminology Updates:
* Changed "SSL Certificate(s)" to "OV TLS Certificate(s)" and "EV SSL Certificate(s)" to "EV TLS Certificate(s)" in the list of certificate types. (`entrust.md`)
* Updated references from "SSL Certificates" to "OV TLS Certificates" and from "EV SSL Certificates" to "EV TLS Certificates" in the compliance sections. (`entrust.md`)
* Updated the description of certificate types to reflect the new terminology. (`entrust.md`)

Version and Date Updates:
* Updated the document version from 3.21 to 3.22 and the date from May 14, 2024, to July 31, 2024. (`entrust.md`)
* Added a new entry in the version history to reflect the change in certificate terminology. (`entrust.md`)

Definitions and Glossary:
* Updated the definitions section to include new terms like "OV TLS Certificate" and updated existing terms to reflect the new certificate terminology. (`entrust.md`) [[1]](diffhunk://#diff-0e8e716980e1c7bb1067b7dd406d364cf9d3f16f231b6fc47710a0cb94c3ecc5L430-R431) [[2]](diffhunk://#diff-0e8e716980e1c7bb1067b7dd406d364cf9d3f16f231b6fc47710a0cb94c3ecc5R543-R544) [[3]](diffhunk://#diff-0e8e716980e1c7bb1067b7dd406d364cf9d3f16f231b6fc47710a0cb94c3ecc5L598-L599) [[4]](diffhunk://#diff-0e8e716980e1c7bb1067b7dd406d364cf9d3f16f231b6fc47710a0cb94c3ecc5R627-R628) [[5]](diffhunk://#diff-0e8e716980e1c7bb1067b7dd406d364cf9d3f16f231b6fc47710a0cb94c3ecc5R680)

### CODE REVIEW

**Comment by vanbroup** [comment]
@bcmorton please review this update from v3.21 > v3.22 as to be in sync with the Word version.

**Comment by vanbroup** [comment]
Any updates on this @bcmorton?

**Comment by bcmorton** [comment]
All edits are correct with the exception of a line in section 3.2.2.1, where "SSL EV Guidelines", should now read "EV SSL Guidelines".

**Comment by bcmorton** [comment]
I made the edit based on my review.

**Pull request merged**
